#ifndef DEFENITIONS_H_
#define DEFENITIONS_H_

#define W_SECTION 8
#define MAX_PIXEL_IDX_IN_SEGMENT (W_SECTION - 1)
#define H_SECTION 8
#define SECTIONS_PER_ROW 4
#define MAX_SECTION_IDX_IN_ROW (SECTIONS_PER_ROW - 1)
#define SECTIONS_PER_COLUMN 2
#define SECTIONS (SECTIONS_PER_ROW * SECTIONS_PER_COLUMN)
#define SCREEN_WIDTH (W_SECTION * SECTIONS_PER_ROW)
#define SCREEN_HEIGHT (H_SECTION * SECTIONS_PER_COLUMN)
#define ROWS 8

#define ROW_L_MASK 0b00111111
#define ROW_H_MASK 0b00000011

#endif
