#ifndef DEFINITIONS_H_
#define DEFINITIONS_H_

#define W_SECTION 8
#define H_SECTION 8
#define SECTIONS_PER_ROW 4
#define SECTIONS_PER_COLUMN 2
#define SECTIONS (SECTIONS_PER_ROW * SECTIONS_PER_COLUMN)
#define SCREEN_WIDTH (W_SECTION * SECTIONS_PER_ROW)
#define SCREEN_HEIGHT (H_SECTION * SECTIONS_PER_COLUMN)
#define ROWS 8

#define TOTAL_WORKERS 2

#endif
