package org.dragberry.ledecorator

const val LEDECORATOR_STATE_CONNECTED = 1001

const val LEDECORATOR_STATE_DISCONNECTED = 1002

const val LEDECORATOR_STATE_CONNECTION_ERROR = 1003

const val LEDECORATOR_DATAFRAME_RECIEVED = 2000

const val LEDECORATOR_SCAN_STARTED = 3000

const val LEDECORATOR_SCAN_STOPPED = 3001

const val LEDECORATOR_ON_SCAN_RESULT = 3002
